package com.mybatis.mapper;

import com.mybatis.entity.Brand;
import com.mybatis.entity.BrandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    long countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int insert(Brand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int insertSelective(Brand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    Brand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int updateByExampleSelective(@Param("row") Brand row, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int updateByExample(@Param("row") Brand row, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int updateByPrimaryKeySelective(Brand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_brand
     *
     * @mbg.generated Fri May 05 09:32:40 CST 2023
     */
    int updateByPrimaryKey(Brand row);
}