# 端口号
server:
  port: 8017

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.110.13.86:3306/flyway?characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      minimum-idle: 5 #最小空闲连接数
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000
      maximum-pool-size: 10 #连接池最大连接数
      auto-commit: true #自动提交 默认true
      pool-name: HikariCP #连接池名称
      max-lifetime: 1800000 #连接池最长生命周期，0表示无限生命周期，默认1800000(30分钟)
      connection-timeout: 30000 #连接超时时间，默认30000
      connection-test-query: SELECT 1